apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/volume/persistentvolume.yaml
- manifests/volume/persistentvolumeclaim.yaml
- manifests/db/service-postgresql.yaml
- manifests/db/postgresql.yaml
- manifests/backend/deployment-backend.yaml
- manifests/backend/service-backend.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: jylhakos/todo-backend-db
  newTag: fdafd7088d04892815ed037cf30ca4f61c7af2f7
