apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todos-gitops-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: todos-repo
  interval: 10m
  path: ./kube-cluster-todos/manifests/**/*
  prune: true
  validation: client